version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    environment:
      LOCALSTACK_HOSTNAME: localstack
      AWS_ENDPOINT_URL: http://localstack:4566
    networks:
      - internal

volumes:
  localstack: {}

networks:
  internal: {}
