version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      internal:
        aliases:
          - localhost.localstack.cloud
          - s3.localhost.localstack.cloud
          - files-bucket.s3.localhost.localstack.cloud
          - execute-api.localhost.localstack.cloud
          - files.execute-api.localhost.localstack.cloud

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    environment:
      LOCALSTACK_HOST: localhost.localstack.cloud:4566
      LOCALSTACK_HOSTNAME: localhost.localstack.cloud
      DEFAULT_REGION: us-east-1
    networks:
      - internal

volumes:
  localstack: {}

networks:
  internal: {}
